package neptune.utils;

public class KeyUtils {

    public static String getKey(int i) {
        return switch (i) {
            case 48 -> "0";
            case 49 -> "1";
            case 50 -> "2";
            case 51 -> "3";
            case 52 -> "4";
            case 53 -> "5";
            case 54 -> "6";
            case 55 -> "7";
            case 56 -> "8";
            case 57 -> "9";
            case 65 -> "A";
            case 66 -> "B";
            case 67 -> "C";
            case 68 -> "D";
            case 69 -> "E";
            case 70 -> "F";
            case 71 -> "G";
            case 72 -> "H";
            case 73 -> "I";
            case 74 -> "J";
            case 75 -> "K";
            case 76 -> "L";
            case 77 -> "M";
            case 78 -> "N";
            case 79 -> "O";
            case 80 -> "P";
            case 81 -> "Q";
            case 82 -> "R";
            case 83 -> "S";
            case 84 -> "T";
            case 85 -> "U";
            case 86 -> "V";
            case 87 -> "W";
            case 88 -> "X";
            case 89 -> "Y";
            case 90 -> "Z";
            case 290 -> "F1";
            case 291 -> "F2";
            case 292 -> "F3";
            case 293 -> "F4";
            case 294 -> "F5";
            case 295 -> "F6";
            case 296 -> "F7";
            case 297 -> "F8";
            case 298 -> "F9";
            case 299 -> "F10";
            case 300 -> "F11";
            case 301 -> "F12";
            case 302 -> "F13";
            case 303 -> "F14";
            case 304 -> "F15";
            case 305 -> "F16";
            case 306 -> "F17";
            case 307 -> "F18";
            case 308 -> "F19";
            case 309 -> "F20";
            case 310 -> "F21";
            case 311 -> "F22";
            case 312 -> "F23";
            case 313 -> "F24";
            case 314 -> "F25";
            case 320 -> "N 0";
            case 321 -> "N 1";
            case 322 -> "N 2";
            case 323 -> "N 3";
            case 324 -> "N 4";
            case 325 -> "N 5";
            case 326 -> "N 6";
            case 327 -> "N 7";
            case 328 -> "N 8";
            case 329 -> "N 9";
            case 330 -> "N .";
            case 331 -> "N /";
            case 332 -> "N *";
            case 333 -> "N -";
            case 334 -> "N +";
            case 335 -> "N ENTR";
            case 336 -> "N =";
            case 340 -> "L SHIFT";
            case 341 -> "L CTRL";
            case 342 -> "L ALT";
            case 343 -> "WIN L";
            case 344 -> "R SHIFT";
            case 345 -> "R CTRL";
            case 346 -> "R ALT";
            case 347 -> "WIN R";
            case 348 -> "MENU";
            case 32 -> "SPACE";
            case 39 -> " '";
            case 44 -> " ,";
            case 45 -> " -";
            case 46 -> " .";
            case 47 -> " /";
            case 59 -> " ;";
            case 61 -> " =";
            case 91 -> " {";
            case 92 -> " \\";
            case 93 -> " }";
            case 96 -> " `";
            case 161 -> "WORLD 1";
            case 162 -> "WORLD 2";
            case 256 -> "ESCAPE";
            case 257 -> "ENTER";
            case 258 -> "TAB";
            case 260 -> "INS";
            case 261 -> "DEL";
            case 262 -> "RIGHT";
            case 263 -> "LEFT";
            case 264 -> "DOWN";
            case 265 -> "UP";
            case 266 -> "P UP";
            case 267 -> "P DOWN";
            case 268 -> "HOME";
            case 269 -> "END";
            case 280 -> "C LOCK";
            case 281 -> "S LOCK";
            case 282 -> "N LOCK";
            case 283 -> "PRT SCN";
            case 284 -> "PAUSE";
            case 0 -> "None";
            default -> "NaN";
        };
    }
}


